"""Initial PostgreSQL schema

Revision ID: 543188a24593
Revises: 
Create Date: 2026-07-19 01:40:19.684949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543188a24593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('blood_group',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-', name='blood_group_request_enum'),
               existing_nullable=False)
        batch_op.alter_column('hospital_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Normal', 'Urgent', 'Emergency', name='urgency_enum'),
               existing_nullable=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Pending', 'Approved', 'Rejected', name='request_status_enum'),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('blood_stock', schema=None) as batch_op:
        batch_op.alter_column('blood_group',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-', name='blood_group_stock_enum'),
               existing_nullable=False)

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('blood_group',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-', name='blood_group_enum'),
               existing_nullable=False)
        batch_op.alter_column('last_donation_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('health_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Fit', 'Unfit', name='health_status_enum'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('admin', 'user', name='user_role_enum'),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'user', name='user_role_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.alter_column('health_status',
               existing_type=sa.Enum('Fit', 'Unfit', name='health_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('last_donation_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('blood_group',
               existing_type=sa.Enum('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-', name='blood_group_enum'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('blood_stock', schema=None) as batch_op:
        batch_op.alter_column('blood_group',
               existing_type=sa.Enum('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-', name='blood_group_stock_enum'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pending', 'Approved', 'Rejected', name='request_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('urgency',
               existing_type=sa.Enum('Normal', 'Urgent', 'Emergency', name='urgency_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('hospital_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('blood_group',
               existing_type=sa.Enum('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-', name='blood_group_request_enum'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
