"""Add appointments campaigns weight next_donation

Revision ID: dcf2c0055e2e
Revises: 543188a24593
Create Date: 2026-07-19 22:34:32.933966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf2c0055e2e'
down_revision = '543188a24593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
